---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(dplyr)
library(tidyverse)
library(factoextra)
library(densityClust)
library(stats)
library(sf)
library(ggpubr)
library(grid)
library(vegan)
library(phytools)
library(picante)
rm(list = ls())
```

```{r}
col_loc = read_csv('./bigquery_export__columbidae_birdlife_urban_locations.csv')
head(col_loc)
```

```{r}
col_ut = read_csv('./bigquery_export__columbidae_birdlife_urban_tolerance.csv')
head(col_ut)
```

```{r}
pigeons = col_ut[,c('species_name', 'urban_tolerance', 'region_count')]
pigeons
```

----------------------------
MNTD, picante
----------------------------
Need to use jetz for this

the mntd function calculates the mean nearest taxon distance (MNTD), the mean distance separating each species in the community from its closest relative

https://cran.r-project.org/web/packages/picante/vignettes/picante-intro.pdf

```{r}
mapping = read_csv('./bigquery_export__columbidae_taxonomic_mapping.csv')
```

```{r}
col_loc_jetz_mapping = left_join(col_loc, mapping)
urban_data = distinct(col_loc_jetz_mapping[col_loc_jetz_mapping$present_in_city == T,c('city_id', 'jetz_scientific_name', 'present_in_city')])

species_in_cities = pivot_wider(urban_data, names_from = jetz_scientific_name, values_from = "present_in_city", values_fill = list(present_in_city = F))
species_in_cities = tibble::column_to_rownames(species_in_cities, var='city_id')
picante_urban_community = as.matrix(species_in_cities)
species_in_cities
```

```{r}
regional_pool_data = distinct(col_loc_jetz_mapping[,c('city_id', 'jetz_scientific_name')])
regional_pool_data$present_in_pool = T

species_in_pools = pivot_wider(regional_pool_data[regional_pool_data$city_id %in% urban_data$city_id,], names_from = jetz_scientific_name, values_from = "present_in_pool", values_fill = list(present_in_pool = F))
species_in_pools = tibble::column_to_rownames(species_in_pools, var='city_id')
picante_pool_community = as.matrix(species_in_pools)
```

```{r}
urban_data_no_feral_pigeon = species_in_cities[species_in_cities$Columba_livia == F,]
picante_urban_community_no_feral_pigeon = as.matrix(urban_data_no_feral_pigeon)
```

```{r}
picante_urban_community_remove_feral_pigeon = as.matrix(species_in_cities[,-c(1)])
```


```{r}
tree <- read.tree("./phylogeny__stage2_hackett_mcc_no_neg.tre")
```

```{r}
tree_pruned_to_columbidae <- ladderize(drop.tip(tree, setdiff(tree$tip.label, colnames(picante_pool_community))))
```

```{r}
phydist <- cophenetic(tree_pruned_to_columbidae)
```

```{r}
pool.mntd.result <- ses.mntd(picante_pool_community, phydist, null.model="taxa.labels", abundance.weighted=FALSE, runs=99)
pool.mntd.result
```

```{r}
city.mntd.result <- ses.mntd(picante_urban_community, phydist, null.model="taxa.labels", abundance.weighted=FALSE, runs=99)
city.mntd.result
```

```{r}
city_nfp.mntd.result <- ses.mntd(picante_urban_community_no_feral_pigeon, phydist, null.model="taxa.labels", abundance.weighted=FALSE, runs=99)
city_nfp.mntd.result
```

```{r}
city_rfp.mntd.result <- ses.mntd(picante_urban_community_remove_feral_pigeon, phydist, null.model="taxa.labels", abundance.weighted=FALSE, runs=99)
city_rfp.mntd.result
```

```{r}
pool.mntd.result$city_name = rownames(pool.mntd.result)
pool.mntd.result$type = 'Regional Pool'

city.mntd.result$city_name = rownames(city.mntd.result)
city.mntd.result$type = 'Urban'

city_nfp.mntd.result$city_name = rownames(city_nfp.mntd.result)
city_nfp.mntd.result$type = 'Urban (No Feral Pigeon)'

city_rfp.mntd.result$city_name = rownames(city_rfp.mntd.result)
city_rfp.mntd.result$type = 'Urban (Feral Pigeon Removed)'

rownames(pool.mntd.result) = NULL
rownames(city.mntd.result) = NULL
rownames(city_nfp.mntd.result) = NULL
rownames(city_rfp.mntd.result) = NULL

mntd.result = rbind(pool.mntd.result[!is.na(pool.mntd.result$mntd.obs), c('city_name', 'mntd.obs', 'type')], city.mntd.result[!is.na(city.mntd.result$mntd.obs), c('city_name', 'mntd.obs', 'type')])

mntd_fp.result = rbind(city_nfp.mntd.result[!is.na(city_nfp.mntd.result$mntd.obs), c('city_name', 'mntd.obs', 'type')], city_rfp.mntd.result[!is.na(city_rfp.mntd.result$mntd.obs), c('city_name', 'mntd.obs', 'type')])

head(mntd.result)
```

```{r}
ggplot(mntd.result, aes(x = type, y = mntd.obs)) + geom_boxplot() + xlab('Community Type') + ylab('MNTD')
```

```{r}
kruskal.test(mntd.result$mntd.obs~mntd.result$type)
```

# The mean nearest taxon distance is significantly lower in regional pools than in urban communities (chi-squard = 85.46, df = 1, p < 0.001)

```{r}
ggplot(rbind(mntd.result, mntd_fp.result), aes(x = type, y = mntd.obs)) + geom_boxplot() + xlab('Community Type') + ylab('MNTD')
```

```{r}
mntd.all.result = rbind(mntd.result, mntd_fp.result)
kruskal.test(mntd.all.result$mntd.obs~mntd.all.result$type)
pairwise.wilcox.test(mntd.all.result$mntd.obs, mntd.all.result$type)
```

Maybe a two-sided t-test is a better test?
------------------------------------------
```{r}
community_change_df = data.frame(
  city = city.mntd.result$mntd.obs,
  pool = pool.mntd.result$mntd.obs,
  id = rownames(species_in_cities)
)
community_change_df = community_change_df[!is.na(community_change_df$city),]
community_change_df
```

```{r}
wilcox.test(community_change_df$pool, community_change_df$city, paired = TRUE)
```

```{r}
community_change_df_l = pivot_longer(community_change_df, names_to = 'type', values_to = 'value', cols = c('pool', 'city'))
community_change_df_l$type = factor(community_change_df_l$type, levels = c('pool', 'city'), labels = c('Regional Pool', 'Urban'))

gg_mntd_change = ggplot(community_change_df_l, aes(x = type, y = value)) + geom_line(aes(group = id), size = 0.1) +  geom_boxplot() + xlab('Community') + ylab('MNTD') + labs(title = "MNTD Change between Regional and Urban Communities", subtitle = "Wilcoxon signed rank (V = 27046, p-value < 2.2e-16)")
gg_mntd_change
```
```{r}
world_distributions <- read_sf('./urban_centres/urban_centres.shp')
world_cities <- distinct(world_distributions[,c('fid', 'geometry')])
names(world_cities) <- c('city_id', 'geometry')
```

```{r}
community_change_df$city_id = as.integer(community_change_df$id)
community_change_df$mntd_increase = ((community_change_df$city / community_change_df$pool) - 1) * 100
world_cities_mntd = left_join(community_change_df, world_cities)
world_cities_mntd = st_sf(world_cities_mntd)
world_cities_mntd
```

```{r}
country_outlines <- read_sf('./world_country_outlines/world-administrative-boundaries.shp')
world_cities <- st_transform(world_cities, crs = st_crs(country_outlines))
```

```{r, fig.width = 8}
library(scales)
gg_mntd_world = ggplot() +  
  geom_sf(data = country_outlines, aes(geometry = geometry)) +
  geom_sf(data = world_cities_mntd, aes(geometry = geometry, color = mntd_increase), show.legend = "point") +
  theme_bw() + theme(legend.position="bottom") + scale_colour_gradient2(
  low = muted("red"),
  mid = "yellow",
  high = "darkgreen",
  midpoint = 0,
  space = "Lab",
  na.value = "grey50",
  guide = "colourbar",
  aesthetics = "colour"
) + guides(color=guide_legend(title="% Increase in MNTD in urban communities compared to regional communities"))
gg_mntd_world
```

```{r}
world_cities_mntd$abs_latitude = abs(st_coordinates(world_cities_mntd)[,2])
model_mntd_by_latitude = glm(data = world_cities_mntd, formula = mntd_increase ~ abs_latitude)
summary(model_mntd_by_latitude)
```

R-squared:
```{r}
with(summary(model_mntd_by_latitude), 1 - deviance/null.deviance)
```

```{r}
gg_mntd_by_latitude = ggplot(world_cities_mntd, aes(x = mntd_increase, y = abs_latitude)) +
  geom_point() +
  geom_smooth(method = "glm") + 
  xlab("% Increase in MNTD") + ylab("Absolute latitude") + 
  labs(title = "MNTD significantly increases in response to urbanisation as towards equator", subtitle = "p = 0.00013, R2 = 0.02")
gg_mntd_by_latitude
```

```{r, fig.height=8,fig.width=8}
library(grid)
library(gridExtra)
grid.arrange(gg_mntd_by_latitude, gg_mntd_world, gg_mntd_change,
  widths = c(2, 1), heights = c(3, 4),
  layout_matrix = rbind(c(1, NA),
                        c(3, 4))
)
```




